nvc -L ./ --work=DUMMY_PLUG -a ../../../Dummy_Plug/src/main/vhdl/core/util.vhd --relaxed
nvc -L ./ --work=DUMMY_PLUG -a ../../../Dummy_Plug/src/main/vhdl/core/reader.vhd --relaxed
nvc -L ./ --work=DUMMY_PLUG -a ../../../Dummy_Plug/src/main/vhdl/core/sync.vhd --relaxed
nvc -L ./ --work=DUMMY_PLUG -a ../../../Dummy_Plug/src/main/vhdl/core/vocal.vhd --relaxed
nvc -L ./ --work=DUMMY_PLUG -a ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_types.vhd --relaxed
nvc -L ./ --work=DUMMY_PLUG -a ../../../Dummy_Plug/src/main/vhdl/core/core.vhd --relaxed
nvc -L ./ --work=DUMMY_PLUG -a ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_core.vhd --relaxed
nvc -L ./ --work=DUMMY_PLUG -a ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_channel_player.vhd --relaxed
nvc -L ./ --work=DUMMY_PLUG -a ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_master_player.vhd --relaxed
nvc -L ./ --work=DUMMY_PLUG -a ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_memory_player.vhd --relaxed
nvc -L ./ --work=DUMMY_PLUG -a ../../../Dummy_Plug/src/main/vhdl/axi4/axi4_models.vhd --relaxed
nvc -L ./ --work=DUMMY_PLUG -a ../../../Dummy_Plug/src/main/vhdl/core/marchal.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/components.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/float_intake_valve.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/float_outlet_valve.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/pipeline_register_controller.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/axi4/axi4_types.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/count_down_register.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/count_up_register.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/delay_adjuster.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/delay_register.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/float_intake_manifold_valve.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/float_outlet_manifold_valve.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/pipeline_register.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/queue_register.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/reducer.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/syncronizer.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/syncronizer_input_pending_register.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/pump/pump_components.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/pump/pump_control_register.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/axi4/axi4_components.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/axi4/axi4_data_port.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/chopper.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/pool_intake_port.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/pool_outlet_port.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/pump/pump_controller_intake_side.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/pump/pump_controller_outlet_side.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/pump/pump_flow_syncronizer.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/axi4/axi4_data_outlet_port.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/axi4/axi4_master_address_channel_controller.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/axi4/axi4_master_transfer_queue.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/queue_arbiter.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/queue_receiver.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/sdpram.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/pump/pump_stream_intake_controller.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/pump/pump_stream_outlet_controller.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/axi4/axi4_master_read_interface.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/axi4/axi4_master_write_interface.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/queue_tree_arbiter.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/axi4/axi4_register_read_interface.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/axi4/axi4_register_write_interface.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/register_access_decoder.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/register_access_syncronizer.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/axi4/axi4_register_interface.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/register_access_adapter.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/queue_arbiter_integer_arch.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/queue_arbiter_one_hot_arch.vhd --relaxed
nvc -L ./ --work=PIPEWORK -a ../../../PipeWork/src/components/sdpram_model.vhd --relaxed
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/sorting_network.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/word.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/core_components.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/word_compare.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/word_pipeline_register.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/oddeven_mergesort_network.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/sorting_network_core.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/word_queue.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/interface/interface.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/merge_sorter_node.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/word_fifo.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/word_reducer.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/examples/argsort_axi/argsort_axi_components.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/examples/argsort_axi/argsort_reader.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/examples/argsort_axi/argsort_writer.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/interface/interface_components.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/interface/merge_reader.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/interface/merge_writer.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/core_intake_fifo.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/core_stream_intake.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/merge_sorter_tree.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/word_drop_none.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/examples/argsort_axi/argsort_axi_reader.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/examples/argsort_axi/argsort_axi_writer.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/interface/interface_controller.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/interface/merge_axi_reader.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/interface/merge_axi_writer.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/core/merge_sorter_core.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/examples/argsort_axi/argsort_axi_interface.vhd
nvc -L ./ --work=MERGE_SORTER -a ../../../src/main/vhdl/examples/argsort_axi/argsort_axi.vhd
nvc -L ./ --work=WORK -a ../../../src/test/vhdl/argsort_axi_test_bench.vhd
