TARGET_DIR        = "."
TARGET            = ["01_introduction.md"          ,
                     "02_word_package.md"          ,
                     "03_word_compare.md"          ,
                     "04_sorting_network.md"       ,
                     "05_bitonic_sorter.md"        ,
                     "06_oddeven_sorter.md"        ,
                     "07_merge_sort_node_single.md",
                     "08_merge_sort_node_multi.md" ,
                     "09_merge_sort_tree.md"       ,
                     "10_merge_sort_core_1.md"     ,
                     "11_merge_sort_core_2.md"     ,
                     "12_merge_sort_core_3.md"     ,
                     "13_argsort.md"               ,
                     "16_bubble_sorter.md"         ,
                     "17_asymmetric_mergesorter.md"].map{|name| File.join(TARGET_DIR, name)}

AKANE_TO_MARKDOWN = File.join("..", "..", "..", "..", "..", "src", "akane_document", "exe", "akane-to-markdown.rb")

TARGET.each do |md|
  base_name   = File.basename(md, ".md")
  akane_name  = File.join("..", "akane", base_name + ".akd")
  image_path  = File.join("..", "akane", base_name + ".img")
  config_name = File.join("."          , base_name + ".yml")
  file md => [akane_name, config_name] do
    sh "#{AKANE_TO_MARKDOWN} --proc #{config_name}"
    Dir.glob("#{image_path}/*.jpg") do |src_image_file|
      num = src_image_file[/akgeo(\d+)/,1]
      dst_image_file = base_name + "_#{num}.jpg"
      FileUtils.cp(src_image_file, dst_image_file)
    end
  end
end

task :default => TARGET

